package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Modelo.profesor;
import Modelo.profesorDAO;
import Modelo.solicitud;
import Modelo.solicitudDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Sistema extends javax.swing.JFrame {

    profesor pr = new profesor();
    profesorDAO profesor = new profesorDAO();
    solicitud sol = new solicitud();
    solicitudDAO solDao = new solicitudDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    public Sistema() {
        initComponents();
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }

    }

    public void Listarprofesor() {
        List<profesor> ListarPr = profesor.Listarprofesor();
        modelo = (DefaultTableModel) Tableprofesor.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarPr.size(); i++) {
            ob[0] = ListarPr.get(i).getNOMBRE();
            ob[1] = ListarPr.get(i).getAPELLIDO();
            ob[2] = ListarPr.get(i).getCÉDULA();
            ob[3] = ListarPr.get(i).getCORREO();
            modelo.addRow(ob);
        }
        Tableprofesor.setModel(modelo);
    }

    public void ListarSolicitud() {
        List<solicitud> ListarSol = solDao.ListarSolicitud();
        modelo = (DefaultTableModel) TableSolicitud.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarSol.size(); i++) {
            ob[0] = ListarSol.get(i).getID_SOLICITUD();
            ob[1] = ListarSol.get(i).getNOMBRE();
            ob[2] = ListarSol.get(i).getAPELLIDO();
            ob[3] = ListarSol.get(i).getFECHA();
            ob[4] = ListarSol.get(i).getDESCRIPCIÓN();
            modelo.addRow(ob);
        }
        TableSolicitud.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSolicitud = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnClases = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreSolicitud = new javax.swing.JTextField();
        txtApellidoSolicitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcionSolicitud = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSolicitud = new javax.swing.JTable();
        btnguardarsoli = new javax.swing.JButton();
        btnactualizarsoli = new javax.swing.JButton();
        btneliminarsoli = new javax.swing.JButton();
        btngenerarpdfsoli = new javax.swing.JButton();
        txtFechaSolicitud = new com.toedter.calendar.JDateChooser();
        txtIdSolicitud = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbmDiaHorario = new javax.swing.JComboBox<>();
        cbmMesHorario = new javax.swing.JComboBox<>();
        cbmAñohorario = new javax.swing.JComboBox<>();
        cbmHoraHorario = new javax.swing.JComboBox<>();
        btnactualizarhorario = new javax.swing.JButton();
        btnagregarhorario = new javax.swing.JButton();
        btnguardarhorario = new javax.swing.JButton();
        btneliminarHorario = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableHorario = new javax.swing.JTable();
        txtidhorarios = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNOMBREP = new javax.swing.JTextField();
        txtAPELLIDOP = new javax.swing.JTextField();
        txtCÉDULAP = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tableprofesor = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtCORREOP = new javax.swing.JTextField();
        btneliminarprofesor = new javax.swing.JButton();
        btnactualizarprofesor = new javax.swing.JButton();
        btnguardarprofesor = new javax.swing.JButton();
        btnagregarprofesor = new javax.swing.JButton();
        txtidhorarios1 = new javax.swing.JTextField();
        txtID_PROFESOR = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtclaseclass = new javax.swing.JTextField();
        cbmHorarioClase = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtDescripcionclase = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tableclases = new javax.swing.JTable();
        btnagregarclase = new javax.swing.JButton();
        btnguardarclase = new javax.swing.JButton();
        btnactualizarclase = new javax.swing.JButton();
        btneliminarclase = new javax.swing.JButton();
        btngenerarpdfclase = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtidclases = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableReportes = new javax.swing.JTable();
        btngenerarpdfReportes = new javax.swing.JButton();
        txtidreportes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1200px-Logo_UDO.svg (1) (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 110));

        btnSolicitud.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (60).png"))); // NOI18N
        btnSolicitud.setText("Solicitud");
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));

        btnHorarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (56).png"))); // NOI18N
        btnHorarios.setText("Horarios");
        btnHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, -1));

        btnPrestamos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (59).png"))); // NOI18N
        btnPrestamos.setText("Profesor");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, -1));

        btnClases.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (58).png"))); // NOI18N
        btnClases.setText("Clases");
        btnClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 140, 50));

        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (57).png"))); // NOI18N
        btnReportes.setText("Reportes");
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 140, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Delegación de Deportes");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Universidad de Oriente");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R (1) (1) (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 810, 140));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtNombreSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSolicitudActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, -1));
        jPanel2.add(txtApellidoSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Descripción");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtDescripcionSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionSolicitudActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescripcionSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        TableSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Horario", "Descripción"
            }
        ));
        TableSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSolicitudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSolicitud);
        if (TableSolicitud.getColumnModel().getColumnCount() > 0) {
            TableSolicitud.getColumnModel().getColumn(0).setPreferredWidth(5);
            TableSolicitud.getColumnModel().getColumn(1).setPreferredWidth(60);
            TableSolicitud.getColumnModel().getColumn(2).setPreferredWidth(60);
            TableSolicitud.getColumnModel().getColumn(3).setPreferredWidth(12);
            TableSolicitud.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 480, 290));

        btnguardarsoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (41).png"))); // NOI18N
        btnguardarsoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarsoliActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardarsoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 40));

        btnactualizarsoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (42).png"))); // NOI18N
        btnactualizarsoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarsoliActionPerformed(evt);
            }
        });
        jPanel2.add(btnactualizarsoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 40));

        btneliminarsoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (37).png"))); // NOI18N
        btneliminarsoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarsoliActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminarsoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 40, 40));

        btngenerarpdfsoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (50).png"))); // NOI18N
        jPanel2.add(btngenerarpdfsoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));
        jPanel2.add(txtFechaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, -1));

        txtIdSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSolicitudActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 20, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombre.setText("Día");
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Mes");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Año");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Hora");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jPanel3.add(cbmDiaHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        jPanel3.add(cbmMesHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        jPanel3.add(cbmAñohorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, -1));

        jPanel3.add(cbmHoraHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, -1));

        btnactualizarhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (42).png"))); // NOI18N
        jPanel3.add(btnactualizarhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnagregarhorario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregarhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (43).png"))); // NOI18N
        jPanel3.add(btnagregarhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        btnguardarhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (41).png"))); // NOI18N
        jPanel3.add(btnguardarhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btneliminarHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (37).png"))); // NOI18N
        jPanel3.add(btneliminarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        TableHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Día", "Mes", "Año", "Hora"
            }
        ));
        jScrollPane4.setViewportView(TableHorario);
        if (TableHorario.getColumnModel().getColumnCount() > 0) {
            TableHorario.getColumnModel().getColumn(0).setPreferredWidth(31);
            TableHorario.getColumnModel().getColumn(1).setPreferredWidth(12);
            TableHorario.getColumnModel().getColumn(2).setPreferredWidth(20);
            TableHorario.getColumnModel().getColumn(3).setPreferredWidth(24);
        }

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 560, 310));
        jPanel3.add(txtidhorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, -1));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Nombre");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Apellido");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Cédula");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel4.add(txtNOMBREP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, -1));
        jPanel4.add(txtAPELLIDOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, -1));
        jPanel4.add(txtCÉDULAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, -1));

        Tableprofesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Correo"
            }
        ));
        Tableprofesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableprofesorMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Tableprofesor);
        if (Tableprofesor.getColumnModel().getColumnCount() > 0) {
            Tableprofesor.getColumnModel().getColumn(0).setPreferredWidth(20);
            Tableprofesor.getColumnModel().getColumn(1).setPreferredWidth(20);
            Tableprofesor.getColumnModel().getColumn(2).setPreferredWidth(20);
            Tableprofesor.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 220));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Correo");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel4.add(txtCORREOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));

        btneliminarprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (37).png"))); // NOI18N
        btneliminarprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarprofesorActionPerformed(evt);
            }
        });
        jPanel4.add(btneliminarprofesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btnactualizarprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (42).png"))); // NOI18N
        btnactualizarprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarprofesorActionPerformed(evt);
            }
        });
        jPanel4.add(btnactualizarprofesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnguardarprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (41).png"))); // NOI18N
        btnguardarprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarprofesorActionPerformed(evt);
            }
        });
        jPanel4.add(btnguardarprofesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btnagregarprofesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregarprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (43).png"))); // NOI18N
        jPanel4.add(btnagregarprofesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));
        jPanel4.add(txtidhorarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, -1));
        jPanel4.add(txtID_PROFESOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 30, -1));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Clase");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Horario");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Profesor");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel5.add(txtclaseclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, -1));

        jPanel5.add(cbmHorarioClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Descripción");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel5.add(txtDescripcionclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 90));

        Tableclases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "Horario", "Profesor", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(Tableclases);
        if (Tableclases.getColumnModel().getColumnCount() > 0) {
            Tableclases.getColumnModel().getColumn(0).setPreferredWidth(20);
            Tableclases.getColumnModel().getColumn(1).setPreferredWidth(20);
            Tableclases.getColumnModel().getColumn(2).setPreferredWidth(60);
            Tableclases.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 250));

        btnagregarclase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (43).png"))); // NOI18N
        jPanel5.add(btnagregarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 40));

        btnguardarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (41).png"))); // NOI18N
        btnguardarclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarclaseActionPerformed(evt);
            }
        });
        jPanel5.add(btnguardarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        btnactualizarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (42).png"))); // NOI18N
        btnactualizarclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarclaseActionPerformed(evt);
            }
        });
        jPanel5.add(btnactualizarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        btneliminarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (37).png"))); // NOI18N
        jPanel5.add(btneliminarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        btngenerarpdfclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (50).png"))); // NOI18N
        jPanel5.add(btngenerarpdfclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, -1));
        jPanel5.add(txtidclases, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 30, -1));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Solicitud", "Profesor", "Estado"
            }
        ));
        jScrollPane3.setViewportView(TableReportes);
        if (TableReportes.getColumnModel().getColumnCount() > 0) {
            TableReportes.getColumnModel().getColumn(0).setPreferredWidth(40);
            TableReportes.getColumnModel().getColumn(1).setPreferredWidth(60);
            TableReportes.getColumnModel().getColumn(2).setPreferredWidth(40);
            TableReportes.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 300));

        btngenerarpdfReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com (50).png"))); // NOI18N
        jPanel6.add(btngenerarpdfReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel6.add(txtidreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 30, -1));

        jTabbedPane1.addTab("tab5", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 810, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorariosActionPerformed

    private void btnClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClasesActionPerformed

    private void txtDescripcionSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionSolicitudActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed

        LimpiarTable();
        Listarprofesor();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void txtNombreSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSolicitudActionPerformed

    private void btnactualizarclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarclaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarclaseActionPerformed

    private void btnguardarclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarclaseActionPerformed

    }//GEN-LAST:event_btnguardarclaseActionPerformed

    private void btnactualizarprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarprofesorActionPerformed
        if ("".equals(txtNOMBREP.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txtNOMBREP.getText()) && !"".equals(txtAPELLIDOP.getText()) && !"".equals(txtCORREOP.getText())) {
                pr.setNOMBRE(txtNOMBREP.getText());
                pr.setAPELLIDO(txtAPELLIDOP.getText());
                pr.setCORREO(txtCORREOP.getText());
                pr.setCÉDULA(Integer.parseInt(txtCÉDULAP.getText()));
                profesor.Modificarprofesor(pr);
                JOptionPane.showMessageDialog(null, " Profesor modificado");
                LimpiarTable();
                Listarprofesor();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnactualizarprofesorActionPerformed

    private void btnguardarprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarprofesorActionPerformed
        if (!"".equals(txtCÉDULAP.getText()) || !"".equals(txtNOMBREP.getText()) || !"".equals(txtCORREOP.getText()) || !"".equals(txtAPELLIDOP.getText())) {
            pr.setCÉDULA(Integer.parseInt(txtCÉDULAP.getText()));
            pr.setNOMBRE(txtNOMBREP.getText());
            pr.setAPELLIDO(txtAPELLIDOP.getText());
            pr.setCORREO(txtCORREOP.getText());
            profesor.RegistrarProfesor(pr);
            LimpiarTable();
            Listarprofesor();
            JOptionPane.showMessageDialog(null, "Profesor registrado.");

        } else {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos.");
        }
    }//GEN-LAST:event_btnguardarprofesorActionPerformed

    private void TableprofesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableprofesorMouseClicked

        int fila = Tableprofesor.rowAtPoint(evt.getPoint());
        txtNOMBREP.setText(Tableprofesor.getValueAt(fila, 0).toString());
        txtAPELLIDOP.setText(Tableprofesor.getValueAt(fila, 1).toString());
        txtCÉDULAP.setText(Tableprofesor.getValueAt(fila, 2).toString());
        txtCORREOP.setText(Tableprofesor.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_TableprofesorMouseClicked

    private void btneliminarprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarprofesorActionPerformed
        if (!"".equals(txtCÉDULAP.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de que desea eliminar?");
            if (pregunta == 0) {
                int cédula = Integer.parseInt(txtCÉDULAP.getText());
                profesor.Eliminarprofesor(cédula);
                LimpiarTable();
                Listarprofesor();
            }
        }
    }//GEN-LAST:event_btneliminarprofesorActionPerformed

    private void btnguardarsoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarsoliActionPerformed

        if (!"".equals(txtNombreSolicitud.getText()) && !"".equals(txtApellidoSolicitud.getText())
                && (txtFechaSolicitud.getDate() != null) && !"".equals(txtDescripcionSolicitud.getText())) {
            sol.setNOMBRE(txtNombreSolicitud.getText());
            sol.setAPELLIDO(txtApellidoSolicitud.getText());
            sol.setFECHA(txtFechaSolicitud.getDate());
            sol.setDESCRIPCIÓN(txtDescripcionSolicitud.getText());
            solDao.RegistrarSolicitud(sol);
            LimpiarSolicitud();
            LimpiarTable();
            ListarSolicitud();
            JOptionPane.showMessageDialog(null, "Solicitud Registrada.");
    }//GEN-LAST:event_btnguardarsoliActionPerformed
        else {
            JOptionPane.showMessageDialog(null, "Campos sin rellenar.");
        }
    }

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        LimpiarSolicitud();
        LimpiarTable();
        ListarSolicitud();
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_btnSolicitudActionPerformed

    private void TableSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSolicitudMouseClicked
        try {
            // TODO add your handling code here:
            int fila = TableSolicitud.rowAtPoint(evt.getPoint());
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            txtIdSolicitud.setText(TableSolicitud.getValueAt(fila, 0).toString());
            txtNombreSolicitud.setText(TableSolicitud.getValueAt(fila, 1).toString());
            txtApellidoSolicitud.setText(TableSolicitud.getValueAt(fila, 2).toString());
            String strDate = (TableSolicitud.getValueAt(fila, 3).toString());
            Date date = null;
            date = formatter.parse(strDate);
            txtFechaSolicitud.setDate(date);
            txtDescripcionSolicitud.setText(TableSolicitud.getValueAt(fila, 4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableSolicitudMouseClicked

    private void btneliminarsoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarsoliActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtIdSolicitud.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la solicitud?");
            if (pregunta == 0) {
                int id = Integer.parseInt(txtIdSolicitud.getText());
                solDao.Eliminarsolicitud(id);
                LimpiarSolicitud();
                LimpiarTable();
                ListarSolicitud();
            }
        }
    }//GEN-LAST:event_btneliminarsoliActionPerformed

    private void btnactualizarsoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarsoliActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtIdSolicitud.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txtNombreSolicitud.getText()) && !"".equals(txtApellidoSolicitud.getText()) && (txtFechaSolicitud.getDate() != null) && !"".equals(txtDescripcionSolicitud.getText())) {
                sol.setNOMBRE(txtNombreSolicitud.getText());
                sol.setAPELLIDO(txtApellidoSolicitud.getText());
                sol.setFECHA(txtFechaSolicitud.getDate());
                sol.setDESCRIPCIÓN(txtDescripcionSolicitud.getText());
                solDao.Modificarsolicitud(sol);
                LimpiarTable();
                LimpiarSolicitud();
                ListarSolicitud();
            JOptionPane.showMessageDialog(null, "Solicitud Modificada.");
            }
            else {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos.");
            }
        }
    }//GEN-LAST:event_btnactualizarsoliActionPerformed

    private void txtIdSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JTable TableHorario;
    private javax.swing.JTable TableReportes;
    private javax.swing.JTable TableSolicitud;
    private javax.swing.JTable Tableclases;
    private javax.swing.JTable Tableprofesor;
    private javax.swing.JButton btnClases;
    private javax.swing.JButton btnHorarios;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JButton btnactualizarclase;
    private javax.swing.JButton btnactualizarhorario;
    private javax.swing.JButton btnactualizarprofesor;
    private javax.swing.JButton btnactualizarsoli;
    private javax.swing.JButton btnagregarclase;
    private javax.swing.JButton btnagregarhorario;
    private javax.swing.JButton btnagregarprofesor;
    private javax.swing.JButton btneliminarHorario;
    private javax.swing.JButton btneliminarclase;
    private javax.swing.JButton btneliminarprofesor;
    private javax.swing.JButton btneliminarsoli;
    private javax.swing.JButton btngenerarpdfReportes;
    private javax.swing.JButton btngenerarpdfclase;
    private javax.swing.JButton btngenerarpdfsoli;
    private javax.swing.JButton btnguardarclase;
    private javax.swing.JButton btnguardarhorario;
    private javax.swing.JButton btnguardarprofesor;
    private javax.swing.JButton btnguardarsoli;
    private javax.swing.JComboBox<String> cbmAñohorario;
    private javax.swing.JComboBox<String> cbmDiaHorario;
    private javax.swing.JComboBox<String> cbmHoraHorario;
    private javax.swing.JComboBox<String> cbmHorarioClase;
    private javax.swing.JComboBox<String> cbmMesHorario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAPELLIDOP;
    private javax.swing.JTextField txtApellidoSolicitud;
    private javax.swing.JTextField txtCORREOP;
    private javax.swing.JTextField txtCÉDULAP;
    private javax.swing.JTextField txtDescripcionSolicitud;
    private javax.swing.JTextField txtDescripcionclase;
    private com.toedter.calendar.JDateChooser txtFechaSolicitud;
    private javax.swing.JTextField txtID_PROFESOR;
    private javax.swing.JTextField txtIdSolicitud;
    private javax.swing.JTextField txtNOMBREP;
    private javax.swing.JTextField txtNombreSolicitud;
    private javax.swing.JTextField txtclaseclass;
    private javax.swing.JTextField txtidclases;
    private javax.swing.JTextField txtidhorarios;
    private javax.swing.JTextField txtidhorarios1;
    private javax.swing.JTextField txtidreportes;
    // End of variables declaration//GEN-END:variables
    private void LimpiarSolicitud() {
        txtIdSolicitud.setText("");
        txtNombreSolicitud.setText("");
        txtApellidoSolicitud.setText("");
        txtFechaSolicitud.setDate(null);
        txtDescripcionSolicitud.setText("");
    }

}
